name: UnityActionsLFS

on:
  pull_request:
    branches: [main, dev]

jobs:
  build:
    name: Build my project âœ¨
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Ignore Unity package manifest changes
      - name: Ignore package manifest changes
        run: |
          git update-index --assume-unchanged "00 Unity Proj/Untitled-26/Packages/manifest.json"
          git update-index --assume-unchanged "00 Unity Proj/Untitled-26/Packages/packages-lock.json"

      # Cache - Updated path
      - uses: actions/cache@v3
        with:
          path: "00 Unity Proj/Untitled-26/Library"
          key: Library-${{ hashFiles('00 Unity Proj/Untitled-26/Assets/**', '00 Unity Proj/Untitled-26/Packages/**', '00 Unity Proj/Untitled-26/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test - Added projectPath
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "00 Unity Proj/Untitled-26"
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build - Added projectPath
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "00 Unity Proj/Untitled-26"
          targetPlatform: WebGL

      # *.asset files related to Addressable Assets appear to be modified by Unitys
      # during building. We should ensure these are committed beforehand to avoid
      # a dirty branch error. Commit author must also be the bot running this job.
      - name: Ensure *.assets are committed
        run: |
          echo "Reached the Ensure *.assets stage."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "00 Unity Proj/Untitled-26/Assets/AddressableAssetsData/AssetGroups/Localization-Asset-Tables-English.asset"
          git commit -m 'chore: Committed any modified *.asset files for AddressableAssetsData.'
          git push

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
